


Spring:
  application:
    name: popcat
  jpa:
    hibernate:
      ddl-auto: update  # (1) ??? ?? ??
    show-sql: false      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://${DB_URL}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
